### ISSUE TITLE
Please publish a MinVer.Lib nuget package

### ISSUE THREAD

**Issue by hexxone** [adamralph/minver#1006]
## Use case(s)

First off, MinVer is an amazing tool and does a pretty good job. Thanks for maintaining it so well!

I want to create another build tool,  similar to "MinVer" which assists in versioning "Jellyfin Plugins" , but has additional functionality like updating json files, creating zip files & hashes etc. for a Release.

As I can see, you have a separate "MinVer.Lib" project, which already contains the "main" logic used for the versioning.

So I thought about integrating "MinVer.Lib" directly, instead of calling the CLI tool externally, but was saddened to see there is no package for it.

## Description

It would be awesome if you could publish the "MinVer.Lib" project as a nuget package as well for developers who wish to integrate your tool directly, without relying on cli.

## Alternatives

Currently I rely on the "version" being passed to the Tool as a CLI-argument after running "minver-cli". 

I could also call the minver CLI tool directly from my tool.  But this relies on the tool to be installed additionally and I would argue, calling a CLI tool from CLI in comparison to directly using it's DLL is rather bad practice when avoidable.

I do not actually need "MinVer-cli" besides that, because the normal "MinVer" nuget package does a pretty good job already :)

Thanks for considering!

**Comment by adamralph** [comment]
@hexxone I appreciate your requirement, but producing a public library package comes at considerable cost. MinVer is a personal project, provided "as-is" for others to consume. I don't mind adding minor features that others need, since external usage tends to feed improvements back into the product, but it's very important that I don't take on too much outside my core use cases in order to keep the product sustainable. Producing a public library package means either exposing the entire public API that MinVer.Lib currently exposes internally to the other projects, or producing a public wrapper around it which only exposes what is required by external projects. It would also mean properly documenting that entire API and avoiding breaking changes where possible. It's quite an investment and I'm not convinced there's enough return for me.

> calling a CLI tool from CLI in comparison to directly using it's DLL is rather bad practice when avoidable

I'm not sure that's true. In fact, the UNIX philosophy states the opposite!

**Comment by adamralph** [comment]
@hexxone given it's almost a month since my last comment, I'm closing this.
