### ISSUE TITLE
height not incremented as expected (or maybe my expectations are wrong)

### ISSUE THREAD

**Issue by mauroservienti** [adamralph/minver#225]
This PR https://github.com/ServiceComposer/ServiceComposer.AspNetCore/pull/18 correctly generates a package versioned as `*-PR.18.alpha.0.*`, so far so good. I was expecting the `height` to increase with each commit, so `*-PR.18.alpha.0.0`, `*-PR.18.alpha.0.1`, `*-PR.18.alpha.0.etc..`, and if my memory works correctly this was the behavior I was observing. First question:

Is my expectation correct?

If this is the case. Due to reasons I force pushed on the PR, clearly visible on GitHub. Since then it seems that on the PR the MinVer generated version is stuck at `*-PR.18.alpha.0.2`, as if the height from the last tag is always 2.

Full build history is available here: https://ci.appveyor.com/project/ServiceComposer/servicecomposer-aspnetcore/history

Am I doing something wrong?

**Comment by adamralph** [comment]
@mauroservienti I checked out the branch and it built `0.0.7-alpha.0.6.nupkg` as expected:

![image](https://user-images.githubusercontent.com/677704/56860315-a6bda200-6995-11e9-9f22-36b0a2e7c405.png)

**Comment by mauroservienti** [comment]
Correct, however on the build server the behavior doesn’t match the local one. https://ci.appveyor.com/project/ServiceComposer/servicecomposer-aspnetcore Look at the last build I just kicked off. It’s still 2 as height, despite rebuilding the PR.

**Comment by mauroservienti** [comment]
Is there any kind of logging I can enable on the build server to better understand what’s going on? Is it enough to enable msbuild verbose logging?

**Comment by adamralph** [comment]
@mauroservienti I know what's happening. The CI build is not building the PR branch. It is building the _test merge_ of the PR branch to the master branch. Since master is already 1 commit ahead of the last tag, that test merge will always be 2 commits ahead of the tag.

**Comment by mauroservienti** [comment]
OK, got it. Thanks @adamralph. Is this the expected behavior or should I expect also CI PR to behave like if I was building a branch? I personally expect the latter, at least this is what I was getting with GitVersion.

**Comment by adamralph** [comment]
@mauroservienti yes, this is the expected behaviour. I suspect GitVersion does some kind of branch-based logic, and anything of that sort is deliberately avoided in MinVer.

Bear in mind that even if this logic exists, during the lifetime of a PR, the same height could be produced from two different builds. E.g. I could push one commit and build height 1, push another commit and build height 2, and then squash the commits and force push and build height 1 again. For that reason, I don't think it's a good idea to push packages to a feed with this logic in place It would be better to embed the build number in the version somehow, and that would with MinVer today. For example: https://github.com/ServiceComposer/ServiceComposer.AspNetCore/pull/22

**Comment by mauroservienti** [comment]
Thanks @adamralph. That’s fine, I like it. Closing this as solved.
