### ISSUE TITLE
Customize default pre-release identifier

### ISSUE THREAD

**Issue by Selmirrrrr** [adamralph/minver#242]
Hi,

As stated in the doc, the default pre-release identifier is `alpha.0`, is there any way change it to `preview` or something else ?

Example : 

```
| * 'Commit # 1'
| * 'Commit # 2 (tag: v1.1.0)' => v.1.1.0
| * 'Commit # 3'               => v.1.1.1-alpha.0.1
| * 'Commit # 4'               => v.1.1.1-alpha.0.2
```

What I would like is : 

```
| * 'Commit # 1'
| * 'Commit # 2 (tag: v1.1.0)' => v.1.1.0
| * 'Commit # 3'               => v.1.1.1-preview.1
| * 'Commit # 4'               => v.1.1.1-preview.2
```

I know that this will (almost) work : 

```
| * 'Commit # 1'
| * 'Commit # 2 (tag: v1.1.0)'                 => v.1.1.0
| * 'Commit # 3 (tag: v1.1.1-preview)'         => v.1.1.1-preview
| * 'Commit # 4'                               => v.1.1.1-preview.2
```

But I'll have to create a new preview tag after each RTM tag... 

My researches pointed me out to 

https://github.com/adamralph/minver/blob/1d2aee6b50e691ed25eea75141ef1991a4e0ee7f/MinVer.Lib/Version.cs#L16

and 

https://github.com/adamralph/minver/blob/1d2aee6b50e691ed25eea75141ef1991a4e0ee7f/MinVer.Lib/Version.cs#L109-L122

I think I'll need to introduce 2 new vars here and override those default values with new ones if corresponding settings are found.

What do you think ? Can this be done this way ? Is there any better way ? I'll be glad the submit a PR if you're ok to accept this new little feature.

Thanks in advance for your support and thanks and lot for this very useful lib.

Best regards,
Selmir

**Comment by adamralph** [comment]
Hi @Selmirrrrr, thanks for raising this.

This is, in fact, a feature I've thought about often, even during the initial developent of MinVer. However, I had no use for it, so I decided to wait until someone asks for it, and now you've asked for it. 🙂

As you say, the implementation should be quite straight forward and not too intrusive, so I'd be happy to accept a PR to add this feature.

BTW - I don't think you want your pre-release identifers to be just `preview`, since then you can only ever tag and release a single `preview`. I would advise using `preview.1`, `preview.2`, etc.:

```
| * 'Commit # 1'
| * 'Commit # 2 (tag: v1.1.0)'           => v.1.1.0
| * 'Commit # 3'                         => v.1.1.1-preview.0.1
| * 'Commit # 4'                         => v.1.1.1-preview.0.2
| * 'Commit # 5 (tag: v1.1.1-preview.1)' => v.1.1.1-preview.1
| * 'Commit # 6'                         => v.1.1.1-preview.1.1
| * 'Commit # 7'                         => v.1.1.1-preview.1.2
| * 'Commit # 8 (tag: v1.1.1-preview.2)' => v.1.1.1-preview.2
```

In this case, the default pre-release identifiers you'd want are `preview.0` rather than just `preview`. This is the reason that the current default is `alpha.0` and not just `alpha`.

It may even be better to restrict customisation to only the pre-release _phase_, i.e. `alpha` vs `preview`. In that case, you would specify something like:

```xml
<MinVerDefaultPreReleasePhase>preview</MinVerDefaultPreReleasePhase>
```

That would result in the default pre-release identifiers being `preview.0` instead of `alpha.0`.

Thoughts?

**Comment by Selmirrrrr** [comment]
Re, thanks for you answer and thoughts.

Your proposition is better than mine, but not exactly what my team wants.

In our current workflow, we only use tags for production releases `v1.1.1`, `v1.1.2` etc, and each commit between two releases is pushed as a `preview` package. You solution will result to all our preview versions to be `vX.X.X-preview.0.X` instead of `vX.X.X-preview.X` 

I know that the issue here is not with MinVer but with our shitty old workflow, I think we can live with this extra `0` in our previews version number. 

I'll try to implement this feature as you proposed and submit a PR when it's ready.

Thanks for your time :)

**Comment by fuzzzerd** [comment]
> It may even be better to restrict customisation to only the pre-release phase, i.e. alpha vs preview. In that case, you would specify something like:
> 
> ```
> <MinVerDefaultPreReleasePhase>preview</MinVerDefaultPreReleasePhase>
> ```
> 
> That would result in the default pre-release identifiers being preview.0 instead of alpha.0.

I like that a lot. That seems like exactly what I want. The current behavior alpha.0, alpha.1, etc is great. But it'd be nice to customize the token that gets appended there: alpha, beta, preview, etc.

**Comment by adamralph** [comment]
Documented as a feature in #246.

**Comment by adamralph** [comment]
FTR #246 has been [released as beta](https://github.com/adamralph/minver/issues/246#issuecomment-517914357).
