### ISSUE TITLE
Using Directory.Build.props and MinVerTagPrefix

### ISSUE THREAD

**Issue by RehanSaeed** [adamralph/minver#330]
Just looking to migrate to this package. I'd like to be able to specify a generic `<MinVerTagPrefix>` in my `Directory.Build.props` file, so I don't have to add it to every project like so:

```xml
<Project>
  <PropertyGroup Label="Build">
    <MinVerTagPrefix>$(PackageId).</MinVerTagPrefix>
  </PropertyGroup>
</Project>
```

Unfortunately, `$(PackageId)` doesn't seem to work and my NuGet package version comes out with a version number that is all zeros even though I have a `Schema.NET.7.0.2` tag:

```
Schema.NET.0.0.0-alpha.0.379.nupkg
```

Any ideas what magic MSBuild property I can use?

**Comment by adamralph** [comment]
Hi @RehanSaeed, I'm sorry, but I've no idea.

@bording any idea?

**Comment by bording** [comment]
The reason you're seeing this happen is related to how MSBuild works. Property values are evaluated in the order that the props & targets files are imported into the project file.

The default value for `$(PackageId)` is assigned in NuGet.Build.Tasks.Pack.targets. Both Directory.Build.props and Directory.Build.targets are imported into the project file before NuGet.Build.Tasks.Pack.targets, so you can't use the default value in those files.

There are a couple of ways to fix this:

1. Manually assign the value of `$(MinVerTagPrefix)` to match the default value of `$(PackageId)`

If you look at NuGet.Build.Tasks.Pack.targets, you'll see that the default value is `$(AssemblyName)`, so you could just use that as well. However, you'll need to do that in Directory.Build.targets because `$(AssemblyName)` doesn't have a value assigned yet in Directory.build.props.

2. Assign `$(MinVerTagPrefix)` inside a target.

If you move your PropertyGroup inside a target, then `$(PackageId)` will have the default value assigned at that point. By convention, you'd still want to move this into Directory.Build.targets instead of Directory.Build.props.

For example:
```
<Target Name="SetTagPrefix" BeforeTargets="MinVer">
  <PropertyGroup Label="Build">
    <MinVerTagPrefix>$(PackageId).</MinVerTagPrefix>
  </PropertyGroup>
</Target>
```

**Comment by adamralph** [comment]
👍 awesome @bording, thanks. That makes sense.

**Comment by RehanSaeed** [comment]
That totally works thanks.

**Comment by RehanSaeed** [comment]
Just a quick FYI, the above solution doesn't seem to work anymore. Instead I've had to:

Directory.Build.props
```csproj
<PropertyGroup Label="Build">
  <MinVerDefaultPreReleaseIdentifiers>preview.0</MinVerDefaultPreReleaseIdentifiers>
  <MinVerVerbosity>normal</MinVerVerbosity>
</PropertyGroup>
```

Project 1
```csproj
  <PropertyGroup Label="Versioning">
    <MinVerTagPrefix>Project1.</MinVerTagPrefix>
  </PropertyGroup>
```

Project 2
```csproj
  <PropertyGroup Label="Versioning">
    <MinVerTagPrefix>$(PackageId).</MinVerTagPrefix>
  </PropertyGroup>
```

It would have been nice to add `<MinVerTagPrefix>$(PackageId).</MinVerTagPrefix>` as the default in Directory.Build.props to avoid repeating it in a few projects but that doesn't work.

Is this correct?

**Comment by RehanSaeed** [comment]
Looks like `$(PackageId)` has changed in MSBuild land and now resolves to an empty string. I'm not sure when this changed.

**Comment by bording** [comment]
@RehanSaeed Which version of the .NET SDK are you using when you're having that problem?

**Comment by RehanSaeed** [comment]
I've been using 7.0.401. See https://github.com/Dotnet-Boxed/Framework.

**Comment by adamralph** [comment]
@RehanSaeed what if you change your `Directory.Build.targets` to do this?

```xml
<MinVerTagPrefix Condition="'$(MinVerTagPrefix)' == ''">$(PackageId).</MinVerTagPrefix>
```

**Comment by adamralph** [comment]
@RehanSaeed

> When did this change?

Assuming something changed in the .NET SDK which affects the order in which these things are set: sorry, I've no idea. Maybe you can ask the .NET team.

I don't know which solution is best for you. You're probably best placed to judge that yourself. Although if you have only a handful of `.csproj` files, then maybe setting `MinVerTagPrefix` in each one is the simplest and easiest. 🤷
