### ISSUE TITLE
"Git tag 1.0" results in file version "0.0.0.0"

### ISSUE THREAD

**Issue by ghorsey** [adamralph/minver#354]
## Version(s)

2.3.0

## To reproduce

1. Create a git tag `1.0`
2. Build Project

## Expected behavior

Expect file version to be `1.0.0.0` (default to 0 for any missing version segments)

## Actual behaviour

File version is `0.0.0.0`

## Workarounds

Always tag your repository with `{Major}.{Minor}.{Patch}`

## Additional context

I would expect that creating a tag of just `1` should default a file version of `1.0.0.0`

**Comment by adamralph** [comment]
Hi @ghorsey, thanks for raising this.

This behaviour is by design. From the [README](https://github.com/adamralph/minver#usage) (emphasis mine):

> ...create a tag with a name which is a _valid SemVer 2.0 version_...

`1.0` is _not_ a valid SemVer 2.0 version, and neither is `1`.

I believe it is not worth the added complexity of supporting version "fragments" such as `1.0` and `1`. Indeed, it's easier to browse version tag history when all tags are valid SemVer 2.0 versions rather than a mix of versions and fragments. Also, if this was supported, there would be three different ways of specifying `1.0.0`: `1.0.0`, `1.0`, and `1`. What would it mean if those three tags where on three different commits? While this would probably not be an intentional scenario, mistakes may be made, and a repo could be left in a state with two commits effectively having a `1.0.0` version. With the current constraint in place, there can only ever be one commit representing version `1.0.0`: the commit tagged with `1.0.0`.

**Comment by ghorsey** [comment]
I think it's poignant that you said SemVer `2.0` and not `2.0.0` 

Hahahaha.

You might want to rethink your perspective.

Software is a human effort.  So there maybe it would be good to write software for people, which still adheres to specs! 👍

**Comment by adamralph** [comment]
> I think it's poignant that you said SemVer `2.0` and not `2.0.0`

The intent is to specify a version _range_ rather than a specific version of SemVer. However, `2.0`, or more explicitly, `2.0.x` is not the correct range. It should be `2.x`. [That has been fixed.](https://github.com/adamralph/minver/pull/355)

---

> You might want to rethink your perspective.
> 
> Software is a human effort. So there maybe it would be good to write software for people, which still adheres to specs! 👍

I don't know what this means.

**Comment by ghorsey** [comment]
What I was trying to say (obviously not well after a couple of drinks😁) is that a large audience for your component is going to be people, like myself, using this awesome component, manually tagging commits.  Since it derives versions from git tags, I think any reasonable person would expect the tag `1.0` would derive the file version `1.0.0.0` and not `0.0.0.0`, which is what felt like a bug or a gap since the result lost information. 

I understand the semantics of saying `2.0` is inaccurate when meaning `2.x` when dealing with version ranges, but this isn't about ranges, its about deriving version numbers from tags.

The point software being a human effort is that often times we write component to be used by other developers vs components to be used by other components.  So I think considering that audience, especially when they are either end users (obviously) or other developers, and setting reasonable defaults goes a long way for these components we write just working under broad circumstances.  Maybe this is just my odd philosophy on software development and various aspects that I find important.

**Comment by augustoproiete** [comment]
@adamralph I'd add my +1 for MinVer to support `major.minor` as well as `major` tags even if they're not valid SemVer 2.x. It would make MinVer even better.

It seems common to have tags such as `v2.0` or `v3` nowadays. I see that often with GitHub actions, for instance. This is straight from the [GitHub's checkout action](https://github.com/actions/checkout):

[![image](https://user-images.githubusercontent.com/177608/85959602-c7a3cd80-b973-11ea-81f4-384b5bf5f1e6.png)](https://github.com/actions/checkout)

**Comment by adamralph** [comment]
@ghorsey @augustoproiete thanks for chiming in.

> Since it derives versions from git tags, I think any reasonable person would expect the tag `1.0` would derive the file version `1.0.0.0` and not `0.0.0.0`

The README clearly states that version tags must be valid SemVer versions. I believe it's reasonable to expect consumers to internalise this. MinVer has been around for a while and is used in many places in the community. This is the first time I've seen an expectation that `1` or `1.0` are recognised.

> It seems common to have tags such as `v2.0` or `v3` nowadays. I see that often with GitHub actions, for instance. This is straight from the [GitHub's checkout action](https://github.com/actions/checkout):

While I see value in "short" version tags for convenience, allowing consumers to write `uses: actions/checkout@v2` instead of `uses: actions/checkout@v2.0.0`, I believe the full version tag should also be present. Otherwise, when upgrading, either manually or automatically, the burden is on consumers to remember to drop the remaining parts of the version. For example, when upgrading from `1.2.3` to `2.0.0`, they would have to drop the `.0.0` and only write `2`, otherwise the upgrade would not work. Indeed, the image posted above by @augustoproiete even demonstrates the practice of having both the short and full versions:

![image](https://user-images.githubusercontent.com/677704/85976931-e2aa2800-b9db-11ea-9f9a-045bbe4d99b9.png)

Another use case for having the full version tags present is search. Finding the tags for versions `2.0.0` or `2.1.0` will be much easier when your tag history actually contains `2.0.0` or `2.1.0`, rather than just `2`, `2.1`, and several other tags starting with `2` or `2.1`.

So, in summary, it seems reasonable to use short version tags for convenience, as synonyms for the full version tags. It seems unwise to use short version tags as _replacements_ for full version tags. For this reason, I'm not convinced there is value in MinVer supporting short version tags.

---

> I understand the semantics of saying `2.0` is inaccurate when meaning `2.x` when dealing with version ranges, but this isn't about ranges, its about deriving version numbers from tags.

This seems to be an unrelated topic that has somehow gotten mixed into this discussion.

---

> The point software being a human effort is that often times we write component to be used by other developers vs components to be used by other components. So I think considering that audience, especially when they are either end users (obviously) or other developers, and setting reasonable defaults goes a long way for these components we write just working under broad circumstances.

To help set expectations, I should probably clarify that _I wrote MinVer for myself_. As stated in the license, it is provided "as-is" for others to consume.

**Comment by bartelink** [comment]
While I appreciate the spirit of the suggestions and the seconding thereof, I believe Adam's stance is absolutely correct; though I'd like to add some further reasons...

Tags added by developers, and specific version suffixes etc feed into file names with wide-ranging implications. 
For instance, I've seen MinVer used as a commandline tool in repos where there's lots of legacy tags of various forms
Being tolerant of (and then needing to document the supported) permutations of aliases of equivalent versions would cause far more problems that it would solve.
