### ISSUE TITLE
Get more version variables from CLI

### ISSUE THREAD

**Issue by chadly** [adamralph/minver#362]
## Use case

I'm using MinVer to successfully version my .NET projects and it works exactly as I would like it to. I'm trying to extend my usage of it to create versioned docker images of my .NET app.

As an example, my .NET app successfully gets versioned to v1.2.3. I would then like to use the minver CLI to get that same version information to version the docker image. As it is now, I can get the string `1.2.3` out of the minver CLI. But I would also like to get these variables that get passed to MSBuild:

> MinVer sets the following custom properties:
> * `MinVerVersion`
> * `MinVerMajor`
> * `MinVerMinor`
> * `MinVerPatch`
> * `MinVerPreRelease`
> * `MinVerBuildMetadata`

I would like to use this information to tag the docker image using the major, minor, patch convention: e.g. `v1`, `v1.2`, and `v1.2.3` so that someone consuming the docker image can depend on the `v1` tag and get all minor/patch updates.

## Description

I'm not sure how it would work. Maybe there can be another command line flag `--environment-variables` or something to set all those version numbers as environment variables which I would then be able to use in the rest of my build script.

**Comment by adamralph** [comment]
@chadly thanks for raising this.

I've been asked this before, and the answer I favour is to deconstruct the version on the consuming side. This can be done reliably because the version format is deterministic. I don't know which language you are using to write your build script, but in C# this is fairly easy:

```C#
var metaSplit = version.Split('+', 2);
var preSplit = metaSplit[0].Split('-', 2);
var rtmSplit = preSplit[0].Split(".");
var (major, minor, patch, preRelease, buildMetadata) =
    (rtmSplit[0], rtmSplit[1], rtmSplit[2], preSplit.ElementAtOrDefault(1), metaSplit.ElementAtOrDefault(1));
```

Returning separate variables from the CLI would require the introduction a serialisation format and a command line option to switch it on, and I'd like to avoid that added complexity if possible.

Also, AFAIK, setting environment variables will not work, since env vars set by a child process are only scoped to that process, and not the calling process.

**Comment by chadly** [comment]
I'm using GitHub Actions with [this action to run MinVer](https://github.com/thefringeninja/action-minver). Now that you mention it, it does seem like this would be a better option to add to the GH Action since that can easily define more than one output and can parse the outputted MinVer version using something like the `semver` npm package.

Thanks for the feedback!

**Comment by adamralph** [comment]
> this would be a better option to add to the GH Action

👍 nice idea.
