### ISSUE TITLE
Suggested process for repo with Nuget libraries using GitHubFlow?

### ISSUE THREAD

**Issue by agilenut** [adamralph/minver#368]
This is just a process question for those using minver.

I have a repo with a few nuget libraries and will be using GitHubFlow. Can someone share their process?

- Do you tag as soon as you feature branch? If so, it kind of assumes you already know if you are making a breaking change or not which I might not know until I'm ready to merge back to master.
- Do you wait to tag until after you merge to master? If so, doesn't that result in double CI builds for the same code in master
- Or, do you push your last change to origin on your feature branch to verify a good CI build, and then tag on the feature branch just before a merge to master? Does that avoid the double build on master?
- Does anyone setup a local nuget feed on their dev machine so they can pull in packages to apps prior to pushing changes to origin? If so, do you do anything special with the tagging locally to make this work well such that you can always update from either the local or CI feed based on what is newer?
- What if there are multiple feature branches in progress by different people? Do you do anything special to prevent conflicts from similar heights across 2 different branches?

Feel free to let me know if there's anything I'm missing.

Thanks!

**Comment by adamralph** [comment]
@agilenut this has been open for a while so I'm closing it now. FWIW:

> - Do you tag as soon as you feature branch? If so, it kind of assumes you already know if you are making a breaking change or not which I might not know until I'm ready to merge back to master.

No. I only tag to release, from my main branch.

> - Do you wait to tag until after you merge to master?

Yes.

> If so, doesn't that result in double CI builds for the same code in master

Yes, but it doesn't bother me.

> - Or, do you push your last change to origin on your feature branch to verify a good CI build, and then tag on the feature branch just before a merge to master? Does that avoid the double build on master?

No.

> - Does anyone setup a local nuget feed on their dev machine so they can pull in packages to apps prior to pushing changes to origin? If so, do you do anything special with the tagging locally to make this work well such that you can always update from either the local or CI feed based on what is newer?

I do set up local nuget feeds on my dev machine for this purpose. I switch them on and off when I need to.

> - What if there are multiple feature branches in progress by different people? Do you do anything special to prevent conflicts from similar heights across 2 different branches?

No, since I don't tend to do anything with the packages produced from those builds. But if you want to, you can embed the PR number or branch into the version, see the [FAQ](https://github.com/adamralph/minver#can-i-use-the-version-calculated-by-minver-for-other-purposes).

---

To get more answers to your questions from other people, I suggest asking in other forums, e.g. [Stack Overflow](https://stackoverflow.com/), the `#dotnet` channel in [ddd-cqrs-es Slack](https://j.mp/ddd-es-cqrs), the C# [Discord](https://discord.com/) server, etc.
