### ISSUE TITLE
PreRelease overrides keeps adding ".0"

### ISSUE THREAD

**Issue by pluqueTheLuxe** [adamralph/minver#428]
My question is about that guy in bold: 1.0.1-PR **.0** .1+test

Major: 1
Minor: 0
Patch: 1
Prerelease: PR
**Who the heck are you!?**: 0
Height: 1
metadata: test

Is there a reason why if I use the defaultPreRelease override it keep adding the `.0` at the end of my override, as opposed of what's written in the FAQ: https://github.com/adamralph/minver#can-i-change-the-default-pre-release-phase-from-alpha-to-something-else

I know the technical reason, it's hardcoded that way here: https://github.com/adamralph/minver/blob/38b456ccb69e908f771fb70c4fdc3baec790cb9d/MinVer.Lib/Version.cs#L19

But is there another reason?

**Comment by adamralph** [comment]
Hi, please read https://github.com/adamralph/minver#usage - it's all explained there.

**Comment by pluqueTheLuxe** [comment]
> Default pre-release identifiers are added. The default pre-release phase is "alpha", but this can be customised.

I read it and it still not explain the "0" behavior ... it says `alpha`, not `alpha.0`. Can you be more specific?

**Comment by adamralph** [comment]
The `0` is the pre-release "number". That is, you don't want to be restricted to a single pre-release, since it's likely you will want a 1st pre-release (`1.0.1.PR.1`), a 2nd pre-release (`1.0.1.PR.2`) etc. The "0th" pre-release is not one that you will release. It's just a way of versioning the interim builds between an RTM and your next pre-release.

E.g. your commits might be versioned as follows:

- `0.0.0.PR.0` (root commit)
- `0.0.0.PR.0.1`
- `0.0.0.PR.0.2`
- `1.0.0.PR.1` (tagged and released)
- `1.0.0.PR.1.1`
- `1.0.0.PR.1.2`
- `1.0.0.PR.2` (tagged and released)
- `1.0.0.PR.2.1`
- `1.0.0.PR.2.2`
- `1.0.0` (tagged and released)
- `1.0.1.PR.0.1` _<-- this is the version you are currently seeing_
- `1.0.1.PR.0.2`
- `1.0.1.PR.1` (tagged and released)
- `1.0.1.PR.1.1`
- `1.0.1.PR.1.2`
- `1.0.1.PR.2` (tagged and released)
- `1.0.1.PR.2.1`
- `1.0.1.PR.2.2`
- `1.0.1` (tagged and released)
- ...

Side note: you may want to consider using something other than "PR" as your pre-release phase. It's easily confused with "pull request". When I first saw it, I thought that's what it meant.

**Comment by pluqueTheLuxe** [comment]
💯 agree on side note! :')

Oh I just understood by re-reading you how-to's that you consider `PR` (in this case) as a pre-release **phase**. That is the important part that I didn't understood on your way to implement the pre-release identifier.

As `1.0.0.PR.1 (tagged and released)` is a manual tag, I wasn't understanding why you wouldn't just append the height after the pre-release identifier .... now it's all clear 👍 

Thanks! Happy holidays!

**Comment by adamralph** [comment]
Great, thanks! You too!

**Comment by lonix1** [comment]
> it says `alpha`, not `alpha.0`

I was also confused by this, and the docs do not explain the concept of "phase".

When I read the above explanation  - which due to the example format, is extremely helpful - it all made sense. It would be good for future readers if it were incorporated somehow into the docs.

Thanks for the excellent example.
